### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by LeNooby09** [Hetsh/docker-mindustry#2]
Persistent storage does not work
I ran 
```
MP="/root/mindustry"
mkdir -p "$MP"
chown -R 1368:1368 "$MP"
```
and then the command to start the docker container but when I put the map files in `/root/mindustry` or `/root/mindustry/config/maps` and reload the maps, they still don't appear

**Comment by Hetsh** [comment]
Hi! I forgot to document the target mount point in the ReadMe. The target should be `/mindustry` not `/root/mindustry`.
